[workspace]
members = [
    ".",
    "crates/chumsky-debug",
]

[package]
name = "chumsky"
version = "1.0.0-alpha.2"
description = "A parser library for humans with powerful error recovery"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Elijah Hartvigsen <elijah.reed@hartvigsen.xyz", "Jakob Wiesmore <runetynan@gmail.com>"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2021"
exclude = [
    "/misc/*",
	"/benches/samples/*",
]

[features]
default = ["std", "spill-stack", "memoization", "sync"]

# Integrate with the standard library
std = []

# Enable nightly-only features like better compiler diagnostics and a Parser impl for ! (the never type)
nightly = []

# Allows deeper recursion by dynamically spilling stack state on to the heap
spill-stack = ["stacker", "std"]

# Allows parser memoisation, speeding up heavily back-tracking parsers and allowing left recursion
memoization = []

# Allows extending chumsky by writing your own parser implementations
extension = []

# Enable support for parser labelling
label = []

# Make builtin parsers such as `Boxed` use atomic instead of non-atomic internals
sync = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
hashbrown = "0.13"
stacker = { version = "0.1", optional = true }
# Enables regex combinators
regex = { version = "1.7", optional = true }

[dev-dependencies]
ariadne = "0.2"
pom = "3.2"
nom = "7.1"
winnow = "0.3"
serde_json = { version = "1.0", features = ["preserve_order"] }
ciborium = { version = "0.2" }
criterion = "0.4.0"
pest = "2.5"
pest_derive = "2.5"
sn = "0.1"
logos = "0.12"

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11", features = ["flamegraph", "criterion"] }

[profile.bench]
debug = true

[[bench]]
name = "json"
harness = false

[[bench]]
name = "lex"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "backtrack"
harness = false

[[bench]]
name = "cbor"
harness = false

[[example]]
name = "nano_rust"
required-features = ["label"]
